// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8qEKd2KXwdIf50U5seRUC1vvM56O6Sc',
    appId: '1:503172661928:web:815c3ec1c9bffb87cbb89d',
    messagingSenderId: '503172661928',
    projectId: 'photos-rg-app',
    authDomain: 'photos-rg-app.firebaseapp.com',
    storageBucket: 'photos-rg-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAD49YNieHD-WlMpgkZz6FHx0e4948bcw',
    appId: '1:503172661928:android:23ecdfad651fe222cbb89d',
    messagingSenderId: '503172661928',
    projectId: 'photos-rg-app',
    storageBucket: 'photos-rg-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB901jv0lxJjEdgrMDYlIAXlPOa5MmalyY',
    appId: '1:503172661928:ios:8df845680b40e23fcbb89d',
    messagingSenderId: '503172661928',
    projectId: 'photos-rg-app',
    storageBucket: 'photos-rg-app.appspot.com',
    iosBundleId: 'com.example.photoMemories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB901jv0lxJjEdgrMDYlIAXlPOa5MmalyY',
    appId: '1:503172661928:ios:f1a2d6885a114d93cbb89d',
    messagingSenderId: '503172661928',
    projectId: 'photos-rg-app',
    storageBucket: 'photos-rg-app.appspot.com',
    iosBundleId: 'com.example.photoMemories.RunnerTests',
  );
}
